# **1. Split the String**

In [ ]:
s="Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


# **2. Use .format() to print the following string.**

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


# **3. In this nest dictionary grab the word "hello"**


In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

print(d['k1'][3]["tricky"][3]['target'][3])

hello


# **Numpy**

In [ ]:
import numpy as np

# **4.1 Create an array of 10 zeros?**
# **4.2 Create an array of 10 fives?**

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# **5. Create an array of all the even integers from 20 to 35**

In [ ]:
import numpy as np
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


# **6. Create a 3x3 matrix with values ranging from 0 to 8**

In [ ]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# **7. Concatinate a and b**
# **a = np.array([1, 2, 3]), b = np.array([4, 5, 6])**

In [ ]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

## **Pandas**

# **8. Create a dataframe with 3 rows and 2 columns**

In [ ]:
import pandas as pd

In [13]:
record = {
"Name": ["Tom", "Jack", "Lucy",
		"Bob", "Jerry", "Alice",
		"Thomas", "Barbie"],
	
"Marks": [9, 19, 20,
			17, 11, 18,
			5, 8],
	
"Status": ["Fail", "Pass", "Pass",
			"Pass","Pass", "Pass",
			"Fail", "Fail"]}

df = pd.DataFrame(record)
df


Name  Marks Status
0     Tom      9   Fail
1    Jack     19   Pass
2    Lucy     20   Pass
3     Bob     17   Pass
4   Jerry     11   Pass
5   Alice     18   Pass
6  Thomas      5   Fail
7  Barbie      8   Fail

# **9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023**

In [ ]:
from datetime import date

def numOfDays(date1, date2):
	return (date2-date1).days

date1 = date(2023, 1, 1)
date2 = date(2023, 2, 10)
print(numOfDays(date1, date2), "days")


40 days


# **10. Create 2D list to DataFrame**

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame.from_records(lists)